otmaponto/match/urls.py
from django.urls import path 
from . import views 

app_name = 'match'
urlpatterns = [
  path('', views.input, name='input'),
  path('fileupload', views.FileUploadView.as_view(), name='fileupload'),
  path('runmatcher_web_url', views.runmatcher_web_url, name='runmatcher_web_url'),
  path('runmatcher_web_file', views.runmatcher_web_file, name='runmatcher_web_file'),
  path('runmatcher', views.runmatcher, name='runmatcher'),
  path('index', views.IndexView.as_view(), name = 'index'),
  # ex: /polls/5/
  path('<int:pk>/', views.DetailView.as_view(), name='detail'),
  # ex: /polls/5/results/
  path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
  # ex: /polls/5/vote/
  path('<int:question_id>/vote/', views.vote, name='vote'),
]

otmaponto/otmaponto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('match/', include('match.urls'))
]

otmaponto/match/models.py
from django.db import models

# Create your models here.

from django.utils import timezone

from .storage import OverwriteStorage

class Document(models.Model):
    owlFile = models.FileField(upload_to='uploaded_ontologies/', storage=OverwriteStorage())

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
      return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
      return self.choice_text

    def was_published_recently(self):
      return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

otmaponto/match/forms.py
from django import forms


class OntologyFileForm(forms.Form):
  
  source = forms.FileField(label='Select source ontology OWL file')
  target = forms.FileField(label='Select target ontology OWL file')

otmaponto/match/views.py
from django.shortcuts import render, get_object_or_404

# Create your views here.

from django.http import HttpResponse, Http404, HttpResponseRedirect

from .models import Question, Choice, Document
from .forms import OntologyFileForm
from .apps import MatchConfig

from django.urls import reverse

from django.views import generic
from django.conf import settings

import os

from django.views.decorators.csrf import csrf_exempt

from .ontology_mapping.src import OTMapOnto as maponto

from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.decorators import api_view
from rest_framework.parsers import FileUploadParser, MultiPartParser, FormParser

import json
from datetime import datetime

def input(request):
  
  #form = OntologyFileForm(request.POST, request.FILES)
  
  #context = {'form':form}
  context = {}

  return render(request, 'match/input.html', context)

@csrf_exempt
def runmatcher(request):

  if request.method == 'POST':
    
    #form = OntologyFileForm(request.POST, request.FILES)

    #postParams = request.FILES.keys()

    
    sourceFile=request.FILES['source']
    sourceDocument = Document(owlFile=sourceFile)
    sourceDocument.save()

    targetFile=request.FILES['target']
    targetDocument = Document(owlFile=targetFile)
    targetDocument.save()
    
    message = "The source owl {} is stored at {} </br>".format(sourceDocument.owlFile.name, sourceDocument.owlFile.url)
    message = message + "The target owl {} is stored at {} </br>".format(targetDocument.owlFile.name, targetDocument.owlFile.url)

    source_url = sourceDocument.owlFile.url
    target_url = targetDocument.owlFile.url

    source_name = sourceDocument.owlFile.name.replace("uploaded_ontologies/", "")
    target_name = targetDocument.owlFile.name.replace("uploaded_ontologies/", "")
    output_url = "./media/alignments/" + source_name + "_" + target_name + '_alignment.rdf'
    

    #align_url = maponto.match("." + source_url, "." + target_url, output_url, None)

    MatchConfig.mapper.align("." + source_url, "." + target_url, output_url)

    with open(output_url, 'r') as file:
      content = file.read()

    return HttpResponse(content)

#########################

@csrf_exempt
@api_view(['POST'])
def runmatcher_web_file(request):

  if request.method == 'POST':
    
    now_str = datetime.now().strftime("%Y_%m_%d-%I_%M_%S_%p")
    
    sourceFile = request.data['source']
    source_url = "./media/uploaded_ontologies/source_{}.rdf".format(now_str)
    with open(source_url, 'w') as file:
        file.write(sourceFile)

   
    targetFile = request.data['target']
    #now_str = datetime.now().strftime("%Y_%m_%d-%I_%M_%S_%p")
    target_url = "./media/uploaded_ontologies/target_{}.rdf".format(now_str)
    with open(target_url, 'w') as file:
        file.write(targetFile)
    
    #now_str = datetime.now().strftime("%Y_%m_%d-%I_%M_%S_%p")
    output_url = "./media/alignments/source_target_alignment_{}.rdf".format(now_str)
    

    MatchConfig.mapper.align(source_url, target_url, output_url)

    with open(output_url, 'r') as file:
      content = file.read()

    return HttpResponse(content)

##########################


@csrf_exempt
def runmatcher_web_url(request):

  if request.method == 'POST':

    source_url=request.POST.get('source')
    target_url=request.POST.get('target')

    head, source_name = os.path.split(source_url)  
    _, target_name = os.path.split(target_url)  

    output_url = head + "/" + source_name + "_" + target_name + '_alignment.rdf'
    

    #maponto.match(source_url, target_url, output_url[5:], None)

    MatchConfig.mapper.align(source_url, target_url, output_url[5:])

    '''
    with open(output_url, 'r') as file:
      content = file.read()
    '''

    return HttpResponse(output_url)

##############################

class FileUploadView(APIView):
  parser_classes = [FileUploadParser,MultiPartParser]

  def post(self, request):
    file_obj = request.data['source']

    return Response(file_obj)

###############################################

class IndexView(generic.ListView):

  template_name = 'match/index.html'
  context_object_name = 'latest_question_list'

  def get_queryset(self): 
    return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
  
  model = Question
  template_name = 'match/detail.html'

class ResultsView(generic.DetailView):
  model = Question
  template_name = 'match/results.html'

def vote(request, question_id):
  question = get_object_or_404(Question, pk=question_id)
  try:
    selected_choice = question.choice_set.get(pk=request.POST['choice'])
  except (KeyError, Choice.DoesNotExist):
    # Redisplay the question voting form.
    return render(request, 'match/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
    })
  else:
    selected_choice.votes += 1
    selected_choice.save()
    # Always return an HttpResponseRedirect after successfully dealing
    # with POST data. This prevents data from being posted twice if a
    # user hits the Back button.
    return HttpResponseRedirect(reverse('match:results', args=(question.id,)))

otmaponto/match/templates/match/detail.html
<form action="{% url 'match:vote' question.id %}" method="post">
  {% csrf_token %}
  <fieldset>
      <legend><h1>{{ question.question_text }}</h1></legend>
      {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
      {% for choice in question.choice_set.all %}
          <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
          <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
      {% endfor %}
  </fieldset>
  <input type="submit" value="Vote">
  </form>

otmaponto/match/templates/match/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'match/style.css' %}">

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'match:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
  

otmaponto/match/templates/match/input.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <title>Run the OTMapOnto Matcher</title>
  </head>
  <body class="bg-light">
    <div class="container">
      <div class="py-5 text-center">
        <img class="d-block mx-auto mb-4" src= {% static 'match/images/CCILogo.png' %} alt="" width="300">
        <h2>Run the OTMapOnto Ontology Matcher</h2>
        <p class="lead">Choose and Upload Two Ontologies as Files and Run the Matcher.</p>
      </div>

      <div class="row">
        <div class="col-md-12">
          <h4>Upload via File</h4>
        </div>
      </div>
      <form id="runViaFile" method="post" action="runmatcher" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">
          <div class="col-md-5">
            <!--
            <span class="form-label">{{form.sourceFile.label_tag}}</span>
            <span class="form-control">{{form.source}}</span>
            -->
            
            <label for="sourceFile" class="form-label">Select source ontology OWL file</label>
            <input class="form-control" type="file" id="source" name="source">
            
          </div>
                
          <div class="col-md-5">
            <!--
            <span class="form-label">{{form.targetFile.label_tag}}</span>
            <span class="form-control">{{form.target}}</span>
            -->
            
            <label for="targetFile" class="form-label">Select target ontology OWL file</label>
            <input class="form-control" type="file" id="target" name="target">
            
          </div>
                
          <div class="col-md-2 d-flex"><!--offset-md-1-->
            <button id="btn-file-match" class="btn btn-primary form-control align-self-end" type="submit">Run Matcher</button>
          </div>
        </div>
      </form>
        
      
      <footer class="my-5 pt-5 text-muted text-center text-small">
        <p class="mb-1">&copy; CCI MRC</p>
        <ul class="list-inline">
          <li class="list-inline-item"><a href="http://www.drexel.edu">Drexe University</a></li>
          <li class="list-inline-item"><a href="http://www.cci.drexel.edu">CCI</a></li>
          <li class="list-inline-item"><a href="https://cci.drexel.edu/mrc/">Metadata Research Center</a></li>
        </ul>
      </footer>
    </div>
    <!-- Optional JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
  </body>
</html>

otmaponto/match/templates/match/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'match:detail' question.id %}">Vote again?</a>